# Generated by Django 4.2.13 on 2024-06-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Отдел')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Фото сотрудника')),
                ('anons', models.CharField(max_length=250, verbose_name='ИМФ')),
                ('full_text', models.TextField(verbose_name='Биография')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
